Pr/cdr 2212 add switch documentation
rei/rei-cedar-docs pull request #1168
Opened 2022-07-26 19:13 UTC by MegMariel

2022-07-26 19:29 UTC, rebecca-larue requested changes
1. Under Overview: Instead of "Toggles are only..." let's say "This component is only" (The toggle is a different component
2. Under Full-width spacing, I think the description should be: "Displays at full width of its container." instead of referring to it being medium-sized, because you can use the full width option at any size.
3. Large: let's get rid of "standard spacing" because large can be in standard or full-width. For the description, can we say something like "Change the size based on where the component is being used."?
4. Custom labels: let's get rid of "medium size, standard spacing" because you can apply custom label styling to any size or spacing
5. I believe Accessibility is always under Overview so is an H3
6. Let's add links to the Don't use when redirections (for instance, Instead, use checkboxes or radio buttons)
7. Under content, there are two bullet points that say the same thing (The label should describe what the control will do when the Switch is on)
8. Let's get rid of Responsiveness—the content under that is for caption and I don't believe we have any content to support this
9. Under Choosing the right component, can we change the intro copy and the table to mimic the new one I created for Toggle Button? I like the intro copy better and the paired down approach to the table seems easier to digest.

2022-07-27 19:24 UTC, MegMariel commented
@rebecca-larue can you review the latest copy edits I made? These include the table update, and copy edits to overview section, H3 updates, links added, Responsiveness section removed. Thanks!

2022-07-27 19:58 UTC, rebecca-larue approved these changes

2022-08-17 19:02 UTC, KenjiCrosland approved these changes

2022-08-17 19:03 UTC, merged